[custom]
;解决DNS泄露，无分流群组
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=🚀 节点选择,[]SRC-IP-CIDR,192.168.0.143/32
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=🏡 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=🤖 AI,https://raw.githubusercontent.com/Hawyan999/hytiktokrule/main/AI.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=DIRECT,[]GEOIP,CN,no-resolve
ruleset=🚀 节点选择,[]FINAL


custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=♻️ 自动选择`url-test`^(?!.*(TikTok|直播|tiktok)).*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🎵 TikTokCA`select`[]⚖️ 负载均衡-散列`[]⚖️ 负载均衡-轮询`[]⚖️ 负载均衡-延迟`.*(TikTok|直播).*
custom_proxy_group=📲 TikTokUS`select`(?=.*tiktok)(?=.*us)`[]⚖️ 负载均衡US-散列`[]⚖️ 负载均衡US-轮询`[]⚖️ 负载均衡US-延迟
custom_proxy_group=🏡 TikTok`select`[]🎵 TikTokCA`[]📲 TikTokUS`[]♻️ 自动选择`[]DIRECT
custom_proxy_group=⚖️ 负载均衡-散列`load-balance`.*(TikTok|直播).*`http://www.google.com/generate_204`300,,strategy=consistent-hashing
custom_proxy_group=⚖️ 负载均衡-轮询`load-balance`.*(TikTok|直播).*`http://www.google.com/generate_204`300,,strategy=round-robin
custom_proxy_group=⚖️ 负载均衡-延迟`load-balance`.*(TikTok|直播).*`http://www.google.com/generate_204`300,,20,strategy=round-robin
custom_proxy_group=⚖️ 负载均衡US-散列`load-balance`(?=.*tiktok)(?=.*us)`http://www.google.com/generate_204`300,,strategy=consistent-hashing
custom_proxy_group=⚖️ 负载均衡US-轮询`load-balance`(?=.*tiktok)(?=.*us)`http://www.google.com/generate_204`300,,strategy=round-robin
custom_proxy_group=⚖️ 负载均衡US-延迟`load-balance`(?=.*tiktok)(?=.*us)`http://www.google.com/generate_204`300,,20,strategy=round-robin
custom_proxy_group=🤖 AI`select`^(?!.*(香港|HK|Hong\s?Kong|🇭🇰|HongKong)).*$



enable_rule_generator=true
overwrite_original_rules=true

